<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GGKU3DELL1099" ignored="0" name="Test" tests="6" failures="1" timestamp="20 Aug 2019 10:20:21 GMT" time="0.099" errors="0">
  <testcase name="test1" time="0.013" classname="Practice.Framework.RetryFailedExample">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="Practice.Framework.RetryFailedExample">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="Practice.Framework.RetryFailedExample">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="Practice.Framework.RetryFailedExample">
    <failure type="java.lang.AssertionError" message="Test1 method in Retry Failed Example class is failed">
      <![CDATA[java.lang.AssertionError: Test1 method in Retry Failed Example class is failed
at Practice.Framework.RetryFailedExample.test1(RetryFailedExample.java:13)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="Practice.Framework.RetryFailedExample"/>
  <testcase name="test3" time="0.002" classname="Practice.Framework.RetryFailedExample"/>
</testsuite> <!-- Test -->
